module.exports = {
  rules: {
    'react/jsx-boolean-value': 0,
    'react/jsx-child-element-spacing': 0,
    'react/jsx-closing-bracket-location': 2,
    'react/jsx-closing-tag-location': 2,
    'react/jsx-curly-newline': 2,
    'react/jsx-curly-spacing': 2,
    'react/jsx-equals-spacing': 2,
    'react/jsx-filename-extension': 0,
    'react/jsx-first-prop-new-line': 2,
    'react/jsx-handler-names': 2,
    'react/jsx-indent': ['error', 2, {
      checkAttributes: true,
      indentLogicalExpressions: true,
    }],
    'react/jsx-indent-props': ['error', 2],
    'react/jsx-key': ['error', { checkFragmentShorthand: true }],
    'react/jsx-max-depth': 0,
    'react/jsx-max-props-per-line': ['error', {
      maximum: 3,
    }],
    'react/jsx-no-bind': 2,
    'react/jsx-no-comment-textnodes': 2,
    'react/jsx-no-duplicate-props': 2,
    'react/jsx-no-literals': 0,
    'react/jsx-no-target-blank': 2,
    'react/jsx-no-undef': 0,
    'react/jsx-no-useless-fragment': 2,
    'react/jsx-one-expression-per-line': 0,
    'react/jsx-curly-brace-presence': 2,
    'react/jsx-fragments': 2,
    'react/jsx-pascal-case': 2,
    'react/jsx-props-no-multi-spaces': 2,
    'react/jsx-props-no-spreading': 0,
    'react/jsx-sort-default-props': 0,
    'react/jsx-sort-props': 0,
    'react/jsx-space-before-closing': 2,
    'react/jsx-tag-spacing': 2,
    'react/jsx-uses-react': 2,
    'react/jsx-uses-vars': 0,
    'react/jsx-wrap-multilines': 2,
  },
};
