module.exports = {
  rules: {
    'array-bracket-newline': 2,
    'array-bracket-spacing': 2,
    'array-element-newline': ['error', 'consistent'],
    'block-spacing': 2,
    'brace-style': 2,
    'camelcase': 2,
    'capitalized-comments': 0,
    'comma-dangle': ['error', 'only-multiline'],
    'comma-spacing': 2,
    'comma-style': 2,
    'computed-property-spacing': 2,
    'consistent-this': 0,
    'eol-last': 2,
    'func-call-spacing': 2,
    'func-name-matching': 0,
    'func-names': 0,
    'func-style': 0,
    'function-call-argument-newline': 0,
    'function-paren-newline': ['error', 'consistent'],
    'id-blacklist': ['error',
      'el',
      'element',
      'elements',
      'item',
      'items',
      'data',
      'results',
    ],
    'id-length': ['error', {
      exceptions: [
        '_',
        '$',
      ],
    }],
    'id-match': 0,
    'implicit-arrow-linebreak': 2,
    'indent': ['error', 2],
    'jsx-quotes': 2,
    'key-spacing': 2,
    'keyword-spacing': 2,
    'line-comment-position': 2,
    'linebreak-style': 0,
    'lines-around-comment': 0,
    'lines-between-class-members': 2,
    'max-depth': 0,
    'max-len': ['error', {
      code: 100,
      tabWidth: 2,
    }],
    'max-lines': 0,
    'max-lines-per-function': 0,
    'max-nested-callbacks': 0,
    'max-params': 0,
    'max-statements': 0,
    'max-statements-per-line': 2,
    'multiline-comment-style': 0,
    'multiline-ternary': 0,
    'new-cap': 2,
    'new-parens': 2,
    'newline-per-chained-call': 2,
    'no-array-constructor': 2,
    'no-bitwise': 2,
    'no-continue': 2,
    'no-inline-comments': 2,
    'no-lonely-if': 2,
    'no-mixed-operators': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-multi-assign': 2,
    'no-multiple-empty-lines': ['error', {
      max: 2,
      maxEOF: 1,
      maxBOF: 1,
    }],
    'no-negated-condition': 0,
    'no-nested-ternary': 2,
    'no-new-object': 2,
    'no-plusplus': 0,
    'no-restricted-syntax': 0,
    'no-tabs': 2,
    'no-ternary': 0,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': 0,
    'no-unneeded-ternary': 2,
    'no-whitespace-before-property': 2,
    'nonblock-statement-body-position': 0,
    'object-curly-spacing': ['error', 'always'],
    'object-property-newline': 2,
    'one-var': ['error', 'never'],
    'one-var-declaration-per-line': 0,
    'operator-assignment': 2,
    'operator-linebreak': 0,
    'padded-blocks': 0,
    'padding-line-between-statements': 0,
    'prefer-object-spread': 1,
    'quote-props': ['error', 'as-needed'],
    'quotes': ['error', 'single'],
    'semi': 2,
    'semi-spacing': 2,
    'sort-keys': 0,
    'sort-vars': 0,
    'space-before-blocks': 2,
    'space-before-function-paren': ['error', {
      "anonymous": "never",
      "named": "never",
      "asyncArrow": "always"
    }],
    'space-in-parens': 2,
    'space-infix-ops': 2,
    'space-unary-ops': ['error', {
      'words': true,
      'nonwords': false,
    }],
    'spaced-comment': 2,
    'switch-colon-spacing': 2,
    'template-tag-spacing': 2,
    'unicode-bom': 0,
    'wrap-regex': 0,
  },
};
